#!/bin/sh

sxhkd &
xrandr --dpi 200 &

bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9
bpsc monitor HDMI1 -d 

# looks
bspc config border_width		4
bspc config window_gap			8
bspc config split_ratio			0.5
bspc config borderless_monocle		true
bspc config gapless_monocle		true
bspc config normal_border_color		"#000000"
bspc config focused_border_color	"#ffffff"

# rules
bspc rule -r "*"
bspc rule -a feh state=floating
bspc rule -a Sxiv state=floating

# autostart
#notify-send "welcome $(whoami)" &

