#!/bin/sh

sxhkd &
xrandr --dpi 200 &

bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9
bpsc monitor HDMI1 -d 

# looks
bspc config border_width		3
bspc config window_gap			12
bspc config split_ratio			0.5
bspc config borderless_monocle		true
bspc config gapless_monocle		true
bspc config normal_border_color		"#151515"
bspc config focused_border_color	"#dedede"

# rules
bspc rule -r "*"
bspc rule -a feh state=floating
bspc rule -a Sxiv state=floating

# autostart
#notify-send "welcome $(whoami)" &

